listener 8883
allow_anonymous true
require_certificate true
use_identity_as_username true
cafile /run/secrets/ca.crt
certfile /run/secrets/server.crt
keyfile /run/secrets/server.key
tls_version tlsv1.2
log_type all
log_type subscribe
log_type unsubscribe
log_type websockets
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
